HotelBookingGarnet/HotelBookingGarnet/ViewModels/SettingsViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using HotelBookingGarnet.Models;
using Microsoft.CodeAnalysis.Options;

namespace HotelBookingGarnet.ViewModels
{
    public class SettingsViewModel
    {
        public User User { get; set; }
        
        [Display(Name = "Current password")]
        [Required(ErrorMessage = "Your current password is required!")]
        [DataType(DataType.Password)]
        public string OldPassword { get; set; }
        
        [Display(Name = "New password")]
        [Required(ErrorMessage = "New password is required!")]
        [DataType(DataType.Password)]
        [StringLength(20, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.",
        MinimumLength = 6)]
        public string NewPassword { get; set; }
        
        [Display(Name = "Confirm password")]
        [Required(ErrorMessage = "Confirmation password is required!")]
        [DataType(DataType.Password)]
        [Compare("NewPassword", ErrorMessage = "Confirmation password and new password doesn't match")]
        public string ConfirmPassword { get; set; }

        public List<string> ErrorMessages { get; set; }
    }
}

HotelBookingGarnet/HotelBookingGarnet/Controllers/AppUser/AppUserController.cs
using System;
using System.Runtime.InteropServices.ComTypes;
using System.Threading.Tasks;
using AutoMapper.Configuration.Internal;
using FluentEmail.Core;
using HotelBookingGarnet.Models;
using HotelBookingGarnet.Services;
using HotelBookingGarnet.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Manage.Internal;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Microsoft.VisualStudio.Web.CodeGeneration.Contracts.Messaging;

namespace HotelBookingGarnet.Controllers
{
    public class AppUserController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IUserService userService;
        private readonly IStringLocalizer<AppUserController> _localizer;

        public AppUserController(UserManager<User> userManager, IUserService userService,
            IStringLocalizer<AppUserController> localizer)
        {
            this.userManager = userManager;
            this.userService = userService;
            _localizer = localizer;
        }

        [Authorize]
        [HttpGet("/settings")]
        public async Task<IActionResult> Settings()
        {
            ViewData["message"] = "";
            var currentUser = await userManager.GetUserAsync(HttpContext.User);
            return View(new SettingsViewModel {User = currentUser});
        }

        [Authorize]
        [HttpPost("/settings")]
        public async Task<IActionResult> Settings(string culture, string returnUrl, SettingsViewModel settingsViewModel)
        {
            var user = await userManager.GetUserAsync(HttpContext.User);
            if (settingsViewModel.OldPassword == null)
            {
                Response.Cookies.Append(
                    CookieRequestCultureProvider.DefaultCookieName,
                    CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                    new CookieOptions {Expires = DateTimeOffset.UtcNow.AddDays(1)});
                return LocalRedirect(returnUrl);
            }

            if (ModelState.IsValid)
            {
                if (settingsViewModel.OldPassword == settingsViewModel.NewPassword)
                {
                    ViewData["error"] = _localizer["New password and old password can't be the same!"];
                    return View(new SettingsViewModel {User = user});
                }

                if (settingsViewModel.NewPassword != settingsViewModel.OldPassword)
                {
                    var result = await userManager.ChangePasswordAsync(user,
                        settingsViewModel.OldPassword, settingsViewModel.NewPassword);
                    if (result.Succeeded)
                    {
                        ViewData["message"] = "Password change was successful!";
                        return View(new SettingsViewModel {User = user});
                    }
                }
            }

            return View(new SettingsViewModel {User = user});
        }

        [HttpGet("/forgotPassword")]
        public IActionResult ForgotPassword()
        {
            return View(new LoginViewModel());
        }

        [HttpPost("/forgotPassword")]
        public async Task<IActionResult> SendRecoveryEmail(LoginViewModel model)
        {
            var user = await userManager.FindByEmailAsync(model.Email);
            ModelState.Remove("Password");

            if (!ModelState.IsValid)
            {
                return View("~/Views/AppUser/ForgotPassword.cshtml", model);
            }

            var errors = await userService.IsEmailPresent(model);
            if (errors.Count != 0)
            {
                model.ErrorMessages = errors;
                return View("~/Views/AppUser/ForgotPassword.cshtml", model);
            }

            var newRandomPassword = userService.GenerateNewPassword();
            await userService.ChangePasswordAsync(newRandomPassword, user);
            await userService.SendRecoveryPasswordAsync(model.Email, newRandomPassword);
            return View("~/Views/AppUser/ResetConfirmation.cshtml");
        }
    }
}

HotelBookingGarnet/HotelBookingGarnet/Views/AppUser/ForgotPassword.cshtml
@model HotelBookingGarnet.ViewModels.LoginViewModel

@{
    ViewData["Title"] = @localizer["Find your email"];
}

<h2>@ViewData["Title"]</h2>
<div class="row">
    <div class="col-md-12">
        <h6>@localizer["Enter your email"]</h6>
        <section>
            @if (Model.ErrorMessages != null)
            {
                @foreach (var error in Model.ErrorMessages)
                {
                    <span class="text-danger">@localizer[@error]</span>
                }
            }
            <form asp-controller="AppUser" asp-action="SendRecoveryEmail" method="post">
                <span asp-validation-for="Email" class="text-danger"></span>
                <hr/>
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control"/>
                </div>
                <button type="submit" class="btn btn-outline-info">@localizer["Request new password"]</button>
            </form>
        </section>
    </div>
</div>

HotelBookingGarnet/HotelBookingGarnet/Views/AppUser/ResetConfirmation.cshtml
<h1>@localizer["NewPassword Email Sent"]</h1>
<h5>@localizer["Please check your email for your new password"]</h5>
<hr/>
<a asp-action="Login" asp-controller="Login">@localizer["Back to Login page"]</a>

HotelBookingGarnet/HotelBookingGarnet/Views/AppUser/Settings.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@model SettingsViewModel

<div class="row">
    <div class="col-md-3"></div>
    <div class="card col-md-6">
        <h2 class="title">@ViewData["Title"]</h2>
        <br/>
        <section>
            <form asp-controller="AppUser" asp-action="Settings" method="post" asp-route-returnUrl="@Context.Request.Path" role="form">
                <div class="rows" class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <h4>@Model.User.UserName @localizer["'s settings"]</h4>
                        </div>
                        <div>
                            <br/>
                            <ul style="list-style-type: none;">
                                <li class="card-subtitle mb-2 text-muted">
                                    <h5>@localizer["Change the language of the page"]</h5>
                                </li>
                            </ul>
                            <hr/>
                            @inject IViewLocalizer Localizer
                            @inject IOptions<RequestLocalizationOptions> LocOptions
                            @{
                                var requestCulture = Context.Features.Get<IRequestCultureFeature>();
                                var cultureItems = LocOptions.Value.SupportedUICultures
                                    .Select(c => new SelectListItem {Value = c.Name, Text = c.DisplayName})
                                    .ToList();
                            }
                            <div class="word-format">
                                @Localizer["Language:"]
                                <select name="culture"
                                        asp-for="@requestCulture.RequestCulture.UICulture.Name"
                                        asp-items="cultureItems">
                                </select>
                            </div>
                            <br/>
                        </div>
                        <br>
                        <div>
                            <ul style="list-style-type: none;">
                                <li class="card-subtitle mb-2 text-muted">
                                    <h5>@localizer["Change your password"]</h5>
                                </li>
                            </ul>

                            <hr/>
                            <div class="md-form">
                                <label asp-for="OldPassword">@localizer["Old Password"]</label>
                                <input asp-for="OldPassword" class="form-control"/>
                                <span asp-validation-for="OldPassword" class="text-danger"></span>
                            </div>
                            <div class="md-form">
                                <label asp-for="NewPassword">@localizer["New Password"]</label>
                                <input asp-for="NewPassword" class="form-control"/>
                                <span class="text-danger">@ViewData["error"]</span>
                                <span asp-validation-for="NewPassword" class="text-danger"></span>
                            </div>
                            <div class="md-form">
                                <label asp-for="ConfirmPassword">@localizer["ConfirmPassword"]</label>
                                <input asp-for="ConfirmPassword" class="form-control"/>
                                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                            </div>
                            <div>
                                <span class="text-success">@ViewData["message"]</span>
                            </div>
                            <div>
                                <button type="submit" class="btn-outline-primary btn-sm">@localizer["Save changes"]</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </section>
    </div>
    <div class="col-md-3"></div>
</div>